name: Tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        node: ['14', '16']
    name: Test (Node v${{ matrix.node }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run TSC
        run: npm run build:check